import asyncio, sys
from playwright.async_api import async_playwright
BASE = sys.argv[1] if len(sys.argv) > 1 else 'http://localhost:8765/'
OUT = '/workspace/astro-editor-mockup/screenshots/'
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(executable_path='/usr/bin/google-chrome', args=['--no-sandbox'])
        pg = await b.new_page(viewport={'width': 1440, 'height': 900}, device_scale_factor=1)
        errs = []
        pg.on('console', lambda m: errs.append(m.text) if m.type == 'error' else None)
        pg.on('pageerror', lambda e: errs.append(str(e)))
        await pg.goto(BASE + '#/', wait_until='networkidle')
        await pg.wait_for_timeout(600)
        await pg.screenshot(path=OUT + '01-projects.png')
        await pg.click('[data-act="connect"]'); await pg.wait_for_timeout(400)
        await pg.screenshot(path=OUT + '08-connect-repo.png')
        await pg.keyboard.press('Escape')
        await pg.click('[data-id="northfork"]'); await pg.wait_for_timeout(900)
        await pg.click('#site [data-key="heroTitle"]'); await pg.wait_for_timeout(150)
        await pg.click('#site [data-key="heroCta"]'); await pg.wait_for_timeout(150)
        await pg.fill('#input', 'Change the headline to “Gear built for the long way up.” and make the button our Ember orange.')
        await pg.dispatch_event('#input', 'input')
        await pg.hover('#site [data-key="heroArt"]', position={'x': 200, 'y': 200}); await pg.wait_for_timeout(300)
        await pg.screenshot(path=OUT + '02-editor-selected-chips.png')
        await pg.click('#send'); await pg.mouse.move(80, 57); await pg.wait_for_timeout(2900)
        await pg.mouse.move(80, 57)
        await pg.screenshot(path=OUT + '03b-agent-working.png')
        await pg.mouse.move(80, 57); await pg.wait_for_timeout(6500)
        await pg.screenshot(path=OUT + '03-after-edit-changes-card.png')
        await pg.click('#changesBtn'); await pg.wait_for_timeout(500)
        await pg.hover('.drawer .commit >> nth=0'); await pg.wait_for_timeout(200)
        await pg.screenshot(path=OUT + '04-changes-drawer.png')
        await pg.click('.drawer [data-act="close-layer"]'); await pg.wait_for_timeout(300)
        await pg.click('#publishBtn'); await pg.wait_for_timeout(500)
        await pg.screenshot(path=OUT + '05-publish-modal.png')
        await pg.click('[data-act="do-publish"]'); await pg.wait_for_timeout(1300)
        await pg.screenshot(path=OUT + '05b-publishing.png')
        await pg.wait_for_timeout(2800)
        await pg.screenshot(path=OUT + '06-publish-success.png')
        await pg.click('.modal [data-act="close-layer"]'); await pg.wait_for_timeout(300)
        await pg.click('#site [data-key="heroSub"]'); await pg.wait_for_timeout(150)
        await pg.click('.actbar [data-act="edit-text"]'); await pg.wait_for_timeout(300)
        await pg.screenshot(path=OUT + '07-direct-edit-popover.png')
        await pg.keyboard.press('Escape'); await pg.keyboard.press('Escape')
        await pg.click('[data-d="mobile"]'); await pg.wait_for_timeout(700)
        await pg.click('#site [data-key="heroCta"]'); await pg.wait_for_timeout(150)
        await pg.click('.actbar [data-act="edit-color"]'); await pg.wait_for_timeout(300)
        await pg.screenshot(path=OUT + '09-mobile-color-popover.png')
        print('errors:', errs)
        await b.close()
asyncio.run(main())
